<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>boo</string>
	</array>
	
	<key>name</key>
	<string>Boo</string>
	
	<key>scopeName</key>
	<string>source.boo</string>

	<key>firstLineMatch</key>
	<string>^#!/.*\bboo(c|js)?[0-9.-]*\b</string>
	<key>foldingStartMarker</key>
	<string>^\s*(def|class)\s+([.a-zA-Z0-9_ &lt;]+)\s*(\((.*)\))?\s*:|\{\s*$|\(\s*$|\[\s*$|^\s*"""(?=.)(?!.*""")</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$|^\s*'''\s*$</string>
	<key>keyEquivalent</key>
	<string>^~B</string>

	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*((static|partial|abstract|final)\s+)*(class)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>meta.class.boo</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.boo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.boo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.boo</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*((static|private|protected|public|virtual|override|abstract|final)\s+)*(def)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>meta.function.boo</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.boo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.boo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.boo</string>
				</dict>
			</dict>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(assert|break|block|callable|case|class|continue|def|debug|else|elif|ensure|enum|event|except|for|from|get|goto|if|import|in|interface|lock|macro|match|namespace|new|of|otherwise|override|pass|raise|ref|return|self|set|struct|then|try|unless|unsafe|using|virtual|while|yield)\b</string>
			<key>name</key>
			<string>keyword.control.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or|not|is)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(isa|as|cast)\b</string>
			<key>name</key>
			<string>keyword.operator.cast.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;\=|&gt;\=|\=\=|&lt;|&gt;|\!\=</string>
			<key>name</key>
			<string>keyword.operator.comparison.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+\=|-\=|\*\=|/\=|//\=|%\=|&amp;\=|\|\=|\^\=|&gt;&gt;\=|&lt;&lt;\=|\*\*\=</string>
			<key>name</key>
			<string>keyword.operator.assignment.augmented.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|\-|\*|\*\*|\b/\b|%|&lt;&lt;|&gt;&gt;|&amp;|\||\^|~</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\=</string>
			<key>name</key>
			<string>keyword.operator.assignment.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(|\)|\[|\]|{|})</string>
			<key>name</key>
			<string>punctuation.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#|//)</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)?(f|F|L)?\b</string>
			<key>name</key>
			<string>constant.numeric.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null|value)\b</string>
			<key>name</key>
			<string>constant.language.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.quoted.triple.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>string.quoted.backtick.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bool|byte|char|date|decimal|double|duck|int|long|object|sbyte|short|single|string|uint|ulong|ushort)\b</string>
			<key>name</key>
			<string>storage.type.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(public|protected|internal|private|abstract|final|static|partial)\b</string>
			<key>name</key>
			<string>storage.modifier.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self|super)\b</string>
			<key>name</key>
			<string>variable.language.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(print|gets|prompt|join|map|array|len|matrix|iterator|shellp|shell|shellm|enemurate|range|reversed|zip|cat|typeof|sizeof)\b</string>
			<key>name</key>
			<string>support.function.builtin.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([a-z_]+[A-Za-z0-9_]*(\s+as\s+([A-Za-z0-9_]+)))\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.boo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.cast.boo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.boo</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-z_]+[A-Za-z_0-9]*\b</string>
			<key>name</key>
			<string>variable.boo</string>
		</dict>
	</array>

	<key>uuid</key>
	<string>86814aa0-4b60-11e2-bcfd-0800200c9a66</string>
</dict>
</plist>
